#!/usr/bin/env python3
import os
import subprocess

################ Adding permissions ###################
cwd = os.getcwd()
files = os.listdir(cwd)


for file in files:
	if '~' not in file:
		os.chmod(file,0o777)
	else:
		continue



################ Git Scripts ###################
# Set the remote and branch
origin = str(input("input the origin (defualt main): "))
branch = str(input("input the branch you want to push to (defualt master): "))
commit_massage = str(input("input the commit massage you want to commit: "))


#run the git and the push command
subprocess.run(['git','add','.'])
subprocess.run(['git','commit','-m',commit_massage])
subprocess.run(['git','push',origin,branch])
