#!/usr/bin/env bash                                                                                                                                   
# Print the domain data                                                                                                                               

if [ $# -eq 2 ]; then
    ANS=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo $2 $ANS | awk 'END {print "The subdomain " $1 " is a " $2 " record and points to " $3}'
elif [ $# -eq 1 ]; then
    dig  "www.$1" | grep -A1 'ANSWER SECTION:'    | awk 'END {print "The subdomain www is a " $4 " record and points to " $5}'
    dig  "lb-01.$1" | grep -A1 'ANSWER SECTION:'  | awk 'END {print "The subdomain lb-01 is a " $4 " record and points to " $5}'
    dig  "web-01.$1" | grep -A1 'ANSWER SECTION:' | awk 'END {print "The subdomain web-01 is a " $4 " record and points to " $5}'
    dig  "web-02.$1" | grep -A1 'ANSWER SECTION:' | awk 'END {print "The subdomain web-02 is a " $4 " record and points to " $5}'
fi
