#!/usr/bin/env bash
# Print the domain data

if [ $# -eq 2 ]; then
    dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk 'END {print "The subdomain " $1 " is a " $4 " record and points to " $5}'
elif [ $# -eq 1 ]; then
    dig  "www.$1" | grep -A1 'ANSWER SECTION:' | awk 'END {print "The domain " $1 " is a " $4 " record and points to " $5}'
    dig  "lb-01.$1" | grep -A1 'ANSWER SECTION:' | awk 'END {print "The domain " $1 " is a " $4 " record and points to " $5}'
    dig  "web-01.$1" | grep -A1 'ANSWER SECTION:' | awk 'END {print "The domain " $1 " is a " $4 " record and points to " $5}'
    dig  "web-02.$1" | grep -A1 'ANSWER SECTION:' | awk 'END {print "The domain " $1 " is a " $4 " record and points to " $5}'
fi
