#!/bin/bash
read -p "Enter The file name you want to create: " FILE_NAME
touch $FILE_NAME
echo "file => ${FILE_NAME} Created"
echo "#!/bin/bash" > $FILE_NAME
echo "shebang added successfully "
chmod u+x $FILE_NAME
echo "Execute permission granted"
echo ">_ Script Compeleted
     	       Have A Nice Day"
