#!/usr/bin/env bash
# Transfer a file securely to remote server
# Using SCP protocole

if [ $# -lt 4 ]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1
fi

# Transfer the file to the user home directory using scp
# Disable strict host key checking with -o option
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
