#!/usr/bin/env bash
# This File Installs NGINX and setup redirect

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
echo 'Ceci n'est pas une page' > /var/www/html/index.html > "/usr/share/nginx/html/404error.html"

sed -i "37i\ \n\tlocation /redirect_me {\n\t\treturn 301 https://egytech.me; \n\t}\n" "/etc/nginx/sites-available/default"
sed -i "37i\ \n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n" "/usr/share/nginx/html/404error.html"

service nginx restart