#!/usr/bin/env bash
# install HAproxy LoadBalancer
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\*

echo "ENABLED=1" >> /etc/default/haproxy
# Configure HAProxy to send traffic to web-01 and web-02 using roundrobin
sudo tee /etc/haproxy/haproxy.cfg 
printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server web-01 100.25.141.227:80 check
    server web-02 100.27.13.92:80 check
" >> /etc/haproxy/haproxy.cfg


# Restart HAProxy service
sudo systemctl restart haproxy

# Enable HAProxy service to start on boot
sudo systemctl enable haproxy
