#!/usr/bin/env bash
# Run nginx as nginx user

# Stop nginx service
service nginx stop

# Change nginx configuration to listen on port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default

# Change user to nginx in nginx.conf
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Start nginx service
service nginx start
